-- 문서 공동 편집 권한. 워크스페이스 멤버는 기본으로 모든 문서를 편집할 수 있고(노션 방식),
-- 문서·폴더별로 'view'(보기만) 또는 'edit'로 덮어쓴다. 문서는 자기 설정 → 가장 가까운 상위 폴더 설정 → 기본값 순으로 따른다.
-- 문서 소유자와 워크스페이스 OWNER는 설정과 관계없이 항상 편집할 수 있다.
CREATE TABLE document_permissions (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id varchar(255)             NOT NULL,
    document_id varchar(255) REFERENCES documents(id) ON DELETE CASCADE,
    folder_id   uuid         REFERENCES folders(id) ON DELETE CASCADE,
    access      varchar(8)               NOT NULL CHECK (access IN ('edit', 'view')),
    updated_by  varchar(255)             NOT NULL,
    updated_at  timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT document_permissions_one_target CHECK (num_nonnulls(document_id, folder_id) = 1),
    CONSTRAINT uq_document_permissions_document UNIQUE (document_id),
    CONSTRAINT uq_document_permissions_folder UNIQUE (folder_id)
);

CREATE INDEX idx_document_permissions_workspace ON document_permissions (workspace_id);

-- 마지막으로 본문을 저장한 사용자. 공동 편집에서 소유자와 수정자가 달라진다.
ALTER TABLE documents ADD COLUMN updated_by varchar(255);
